### ISSUE TITLE
Background Color

### ISSUE THREAD

**Issue by soheil** [jsdf/react-native-refreshable-listview#10]
It'd be nice either to default to transparent or allow to change the white background color behind the spinner:
![screen shot 2015-04-30 at 4 48 31 pm](https://cloud.githubusercontent.com/assets/287288/7424680/259eff62-ef59-11e4-9039-567848f3fa26.png)

Also how do you align the spinner vertically in the middle?

**Comment by stetro** [comment]
Hey sohell,
you can easily override all those styles by adding the stylesheet attribute to the component and setting up a stylesheet in the following structure:

```JavaScript
var pullDownStyle = StyleSheet.create({
  wrapper: {
    height: 60,
    marginTop: 10,
  },
  container: {
    flex: 1,
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  loading: {
    height: 60,
  },
})
```
```XML
      <RefreshableListView
        stype={styles.list}
        pageSize='4'
        minPulldownDistance='60'
        stylesheet={pullDownStyle}
        dataSource={this.state.dataSource}
        renderRow={this.renderNewsItem}
        loadData={this.loadNewsFeed}
        refreshDescription="Refresh"/>);
```

**Comment by JonasJonny** [comment]
Thank you @stetro. It was not clear from documentation.

But as @soheil wrote. Default backgroundColor should be transparent and not white.

**Comment by stetro** [comment]
Thats right :) I just checked the implementation

**Comment by JonasJonny** [comment]
Also there should be an option to change spinner color to different color (#123456, ...).

<ActivityIndicator color="#123456" style={styles.activityIndicator} />

**Comment by jsdf** [comment]
In the next major version the refreshing header content (spinner and text) will be a separate component which you can customise or replace entirely.

**Comment by stetro** [comment]
+1

**Comment by jsdf** [comment]
In v1.0.0 this is now covered by passing in a customised `RefreshingIndicator` component: https://github.com/jsdf/react-native-refreshable-listview#customising-the-refresh-indicator-spinner
