### ISSUE TITLE
Navigation Breaks Images

### ISSUE THREAD

**Issue by soheil** [jsdf/react-native-refreshable-listview#11]
Assuming you have a RefreshableListView as the root component. If you push components two levels deep in the navigator and pop back to root any images in the RefreshableListView no longer get updated if you change the image URL on the state.

```
              <Image
                source={{uri: rowData.posters.thumbnail}}
                style={styles.cellImage} />
```

if you change `rowData.posters.thumbnail` image does not update anymore.

**Comment by jsdf** [comment]
Does this happen with a regular ListView?

**Comment by soheil** [comment]
Yes actually it does, I have already posted an issue to React Native repo: https://github.com/facebook/react-native/issues/1161

**Comment by jsdf** [comment]
Are you sure you've used the ListView `rowHasChanged` callback correctly? So that if `rowData.posters.thumbnail` changes it will return false?

**Comment by soheil** [comment]
Yes because I can see the text in the row changing but not the image!

**Comment by jsdf** [comment]
Ahh okay, fair enough. If you're satisfied that it's an issue in the underlying React Native ListView then feel free to close this issue as it should be resolved by any fix made in React Native.

**Comment by soheil** [comment]
sure let's wait for them. Thanks.
