### ISSUE TITLE
Spinner Doesn't Show Up

### ISSUE THREAD

**Issue by soheil** [jsdf/react-native-refreshable-listview#12]
With the trunk version of React Native, the spinner no longer shows up on pull down.

**Comment by jsdf** [comment]
The trunk version? Do you mean 0.4.2? If so, I'm not able to reproduce the issue.

**Comment by soheil** [comment]
The version when you do a Github pull.

**Comment by jsdf** [comment]
Can you give me the commit SHA of the version of react-native which is presenting the issue?
Or better even better, a minimal demo of the issue? As I have been unable to reproduce it.

**Comment by thomasrose** [comment]
I could not get the spinner to appear when passing a renderHeader method, it works fine when using renderSectionHeader

**Comment by jsdf** [comment]
Oh. I'm guessing you guys aren't rendering the refreshing indicator which is passed as the first arg to renderHeader. If this API is tripping people up then I guess I should change it. Here's the correct usage:

```js
React.createClass({
  renderHeader(refreshingIndicator) {
    return (
      <View>
        <Text>My custom header</Text>
        {/*  you MUST render the refreshingIndicator (which is passed in as the first argument) */}
        {refreshingIndicator}
      </View>
    )
  },
  render() {
    return (
      <RefreshableListView renderHeader={this.renderHeader} />
    )
  }
})
``

**Comment by jsdf** [comment]
Published a new version where `renderHeader` becomes `renderHeaderWrapper`
