### ISSUE TITLE
render header method

### ISSUE THREAD

**Issue by LeezQ** [jsdf/react-native-refreshable-listview#15]
if I add a `renderHeader` method in `RefreshableListView` component, the refreshable will not work, is this a bug ?

**Comment by jsdf** [comment]
The first argument passed to renderHeader is the refreshing indicator which you need to display as part of your custom header

**Comment by jsdf** [comment]
I've published a new version (1.2.0) which changes the `renderHeader` method to `renderHeaderWrapper`. Please have a read of the documentation and see if this is suitable for your purpose.
