### ISSUE TITLE
refreshingIndicator is empty on renderHeaderWrapper function

### ISSUE THREAD

**Issue by txixyo** [jsdf/react-native-refreshable-listview#21]
Hello. First of all, nice plugin. :)

I have the following code:

    <RefreshableListView
              ref="PostView"
              renderHeaderWrapper={this.renderHeader}

My renderHeader function looks like this:

    renderHeader: function(refreshingIndicator) {
        console.log(refreshingIndicator);

However, my console log returns null. Got any idea why? Am I doing something wrong?

**Comment by jsdf** [comment]
That argument is `null` when not currently refreshing. The refreshing indicator is only rendered while refreshing. Consider that in React, rendering `null` just means 'render no content'.

**Comment by txixyo** [comment]
Ah yes, thanks for the clarification!
