### ISSUE TITLE
Required prop `isTouching` and `isWaitingForRelease` not specified in `RefreshingIndicator`

### ISSUE THREAD

**Issue by niftylettuce** [jsdf/react-native-refreshable-listview#34]

**Comment by niftylettuce** [comment]
![screen shot 2016-01-03 at 6 03 40 pm](https://cloud.githubusercontent.com/assets/523141/12081354/5931f6e6-b244-11e5-9574-868dc8284306.png)
![screen shot 2016-01-03 at 6 01 21 pm](https://cloud.githubusercontent.com/assets/523141/12081355/5937a5d2-b244-11e5-9493-700a3af75139.png)

**Comment by mauron85** [comment]
+1

**Comment by pjcabrera** [comment]
+1

**Comment by realjamie** [comment]
+1

**Comment by natorojr** [comment]
Eliminating this warning would be greatly appreciated. Thanks.
