### ISSUE TITLE
This package should be deprecated

### ISSUE THREAD

**Issue by dhrrgn** [jsdf/react-native-refreshable-listview#39]
React Native v0.18.0 now has this functionality built into the ListView/ScrollView.  See here: https://github.com/facebook/react-native/commit/44f7a00e95af91dbdfc9feb4f097558b85a8917b

As such, I believe this package should be marked as deprecated (i.e. for use only with RN versions prior to 0.18.0), and point to the docs here: http://facebook.github.io/react-native/docs/refreshcontrol.html

**Comment by strefethen** [comment]
@dhrrgn I suggest a closer look at this module as it's _significantly_ more than just "pull-to-refresh" listview. It's well thought out with great flexibility for numerous things not supported on the stock listview. My company has been using in production for many months.

Kudos to the author.
