### ISSUE TITLE
It can be automatically refresh?

### ISSUE THREAD

**Issue by developerworks** [jsdf/react-native-refreshable-listview#4]
When some events happened, if there have a method to trigger a refreshing automatically ?

**Comment by jsdf** [comment]
That's an interesting idea, I'm not sure what would be the most useful way to implement it. One possibility would be to call a method on the component via a ref, though that's only useful if it's parent is the one doing the refreshing. Another option might be to provide a [Higher-Order Component](https://gist.github.com/sebmarkbage/ef0bf1f338a7182b6775) which you can incorporate into your own component and interact with the 'refreshing' state manually. Or maybe just allow you to pass in a 'refreshing' prop which would supercede the internal 'refreshing' state.

**Comment by jsdf** [comment]
This requirement is now covered by the `ControlledRefreshableListView` component.
