### ISSUE TITLE
Can only get 2.0.0-beta2

### ISSUE THREAD

**Issue by behl1** [jsdf/react-native-refreshable-listview#42]
Can only get the second version of the beta using the given npm command. Anyway to get beta4?
Thanks.

**Comment by behl1** [comment]
Anyone?

**Comment by philipshurpik** [comment]
@jsdf Please publish 2.0.0-beta4 to npm
Thanks

**Comment by jsdf** [comment]
Sorry! I've published the missing versions

**Comment by behl1** [comment]
No Problem! Thanks a lot!
