### ISSUE TITLE
How to Pull up refresh listview?

### ISSUE THREAD

**Issue by qingfeng** [jsdf/react-native-refreshable-listview#6]
How should I do? thanks

**Comment by jsdf** [comment]
I'm not sure what your question is. Do you mean you want refresh when scrolling to the bottom of the list? Have a look at the ListView onEndReached prop: https://facebook.github.io/react-native/docs/listview.html#onendreached

There's an example of how you could use it here: https://github.com/facebook/react-native/blob/75f6d2b8f99173215175d01fccd104255f26bd9d/Examples/Movies/SearchScreen.js#L161-L214

**Comment by czciii** [comment]
@jsdf  ths.that's what i need.
ps：u  are so handsome and looks cool .haha

**Comment by karlbright** [comment]
+1 to @czciii
